language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.1.400

env:
  global:
    - marten_testing_database="Host=localhost;Port=5432;Database=marten_test;Username=postgres;Password=Password12!"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-plv8

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
  - travis_retry npm install

before_script:
  - psql -c 'create database marten_test;' -U postgres
  - psql -d marten_test -c 'create extension if not exists plv8;'

script:
  - dotnet run -p martenbuild.csproj -- ci
