version: 2.0.{build}

branches:
  only:
    - appveyor_integration

platform: Any CPU

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  marten-testing-database: "Host=localhost;Port=5432;Database=marten_test;Username=postgres;Password=Password12!"
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.5
  PG_PLV8_EXTENSION_ZIP_FILENAME: pg95plv8jsbin_w64
  PG_DB: marten_test

services: 
  - postgresql95

install:
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%
  - curl -L -O -S -s http://www.postgresonline.com/downloads/%PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - 7z x %PG_PLV8_EXTENSION_ZIP_FILENAME%.zip
  - xcopy /s /y /d %PG_PLV8_EXTENSION_ZIP_FILENAME% "%POSTGRES_PATH%\"

before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - createdb %PG_DB%
  - psql -d %PG_DB% -c "create extension if not exists plv8;"
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - dotnet restore .\src\Marten.sln

build_script:
  - dotnet build .\src\Marten.sln

test_script:
  - dotnet test .\src\Marten.Testing\Marten.Testing.csproj