trigger:
  - master
  - azure_pipelines_ci

resources:
  containers:
    - container: ci_container_linux
      image: ubuntu:16.04
      options: "--name ci_container_linux -v /usr/bin/docker:/tmp/docker:ro"
    - container: pg11
      image: ionx/postgres-plv8:11.1
    - container: pg10
      image: ionx/postgres-plv8:10.6
    - container: pg9.6
      image: clkao/postgres-plv8:9.6

pool:
  vmImage: 'ubuntu-16.04'

container: ci_container_linux

variables:
  config: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  dotnetcore_version: 2.1.400
  node_version: 10.x
  pg_db: marten_test
  marten_testing_database: "Host=localhost;Port=5432;Database=marten_test;Username=postgres;Password=Password12!"

strategy:
  matrix:
    # pg9.6:
    #   postgresService: pg9.6
    # pg10:
    #   postgresService: pg10
    pg11:
      postgresService: pg11

services:
  postgres: $[ variables['postgresService'] ]

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: $(dotnetcore_version)
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
  - script: |
      /tmp/docker exec -t -u 0 ci_container_linux \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
      sudo apt-get update &&
      sudo apt-get install -y libicu-dev
      sudo apt-get install -y postgresql-client
      createdb $(pg_db)
      psql -d $(pg_db) -c "create extension if not exists plv8;"
      chmod +x build.sh
      dotnet --info
      npm install
      echo "<?xml version='1.0' encoding='utf-8'?><configuration><packageSources><add key='MyFeed' value='https://pkgs.dev.azure.com/xyz/_packaging/xyz/nuget/v3/index.json' /></packageSources><packageSourceCredentials><ByThey><add key='Username' value='VSTS' /><add key='ClearTextPassword' value='$(System.AccessToken)' /></ByThey></packageSourceCredentials></configuration>" > NuGet.Config
    displayName: Before build
  - script: ./build.sh ci
    displayName: Build
