trigger:
  batch: true
  branches:
    include:
      - master
      - azure_pipelines_ci
      - refs/tags/*

resources:
  containers:
    - container: pg11
      image: ionx/postgres-plv8:11.1
      options: --name postgres
      ports:
        - 5432:5432
    - container: pg10
      image: ionx/postgres-plv8:10.6
      options: --name postgres
      ports:
        - 5432:5432
    - container: pg9.6
      image: clkao/postgres-plv8:9.6
      options: --name postgres
      ports:
        - 5432:5432

variables:
  config: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  dotnet_core_version: 2.1.400
  node_version: 10.x
  pg_db: marten_test
  marten_testing_database: "Host=localhost;Port=5432;Database=marten_test;Username=postgres;Password=Password12!"

jobs:
  - job: Build
    timeoutInMinutes: 20
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        # pg9.6:
        #   postgresService: pg9.6
        # pg10:
        #   postgresService: pg10
        pg11:
          postgresService: pg11
    services:
      postgres: $[ variables['postgresService'] ]
    steps:
      - task: DotNetCoreInstaller@0
        displayName: Install .Net Core
        inputs:
          version: $(dotnet_core_version)
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
          versionSpec: $(node_version)
      - script: |
          #sudo apt-get update
          #sudo apt-get install -y libicu-dev libcurl3 postgresql-client
          export PG_CONTAINER_NAME=docker ps --filter expose=5432/tcp --format {{.Names}}
          echo $PG_CONTAINER_NAME
          docker exec $PG_CONTAINER_NAME psql -U postgres -c 'create database $(pg_db);'
          docker exec $PG_CONTAINER_NAME psql -U postgres -d $(pg_db) -c "create extension if not exists plv8;"
        displayName: Create db and add plv8 extension
      - script: ./build.sh ci
        displayName: Build
  - job: Publish
    dependsOn: Build
    # run publish only if all build jobs succeed and a GitHub tag is created
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DotNetCoreInstaller@0
        displayName: Install .Net Core
        inputs:
          version: $(dotnet_core_version)
      - script: ./build.sh pack
        displayName: Create NuGet Packages
      - task: NuGetCommand@2
        displayName: Publish packages to NuGet
        inputs:
          command: 'push'
          nuGetFeedType: 'external'
          packagesToPush: '$(Build.Repository.LocalPath)/artifacts/*.nupkg'
          publishFeedCredentials: 'NuGetServiceConnection'
      - task: NuGetCommand@2
        displayName: Publish symbol packages to NuGet
        inputs:
          command: 'push'
          packagesToPush: '$(Build.Repository.LocalPath)/artifacts/*.snupkg'
          publishFeedCredentials: 'NuGetServiceConnection'
