FROM microsoft/dotnet:2.1-sdk-bionic

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get -y autoclean

ENV NODE_VERSION 10.11.0
ENV marten_testing_database "Host=testdb;Port=5432;Database=marten_test;Username=postgres;Password=Password12!"

RUN curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
  && source /root/.nvm/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm use $NODE_VERSION

ENV NVM_DIR /root/.nvm
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

WORKDIR /app
RUN chmod +x build.sh

ENTRYPOINT ["/bin/bash"]